
# HELP MENU
all: help
help:
	@echo ""
	@echo "# Help Menu"
	@echo ""
	@echo "   Need some help?"
	@echo ""
	@echo "   ## Installation"
	@echo ""
	@echo "   .  make install              - Install dependencies"
	@echo ""
	@echo "   ## Development"
	@echo ""
	@echo "   .  make start                - Start packager"
	@echo "   .  make build-android        - Build Android application"
	@echo ""

install:
	@echo ""
	@echo "====================== Installing project dependencies ======================="
	@echo ""
	yarn install

start:
	@echo ""
	@echo "====================== Start packager ======================="
	@echo ""
	yarn run start

build-android:
	@echo ""
	@echo "====================== Build Android application ======================="
	@echo ""
	react-native run-android

