imports:
    - { resource: jane.yml }
    - { resource: listeners.yml }

services:
    chauffe_marcel.marcel:
        class: ChauffeMarcel\Marcel
        arguments:
            - '@chauffe_marcel.particle'
            - '@chauffe_marcel.heating_strategy'

    chauffe_marcel.particle:
        class: ChauffeMarcel\Remote\Particle
        arguments:
            - '%particle_device_id%'
            - '%particle_access_token%'

    chauffe_marcel.storage:
        class: ChauffeMarcel\Configuration\Storage
        arguments:
            - '%kernel.root_dir%/../var/storage.json'
            - '@chauffe_marcel.api.serializer'

    chauffe_marcel.heating_strategy:
        class: ChauffeMarcel\Configuration\HeatingStrategy

    chauffe_marcel.api.serializer.normalizers:
        class: ArrayObject
        factory: [ChauffeMarcel\Api\Normalizer\NormalizerFactory, create]
        public: false

    chauffe_marcel.api.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            - '@chauffe_marcel.api.serializer.normalizers'
            - ['@jane.serializer.json_encoder', '@jane.serializer.raw_encoder']

    chauffe_marcel.command.periodic:
        class: ChauffeMarcel\Command\PeriodicMarcelCommand
        arguments:
            - '@chauffe_marcel.storage'
            - '@chauffe_marcel.marcel'
        tags:
            - { name: console.command }


