default:
    resource: ChauffeMarcel\Controller\DefaultController
    type:     annotation

time_slot:
    resource: ChauffeMarcel\Controller\TimeSlotController
    type:     annotation

mode:
    resource: ChauffeMarcel\Controller\ModeController
    type:     annotation
