# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    chauffe_marcel.particle:
        class: ChauffeMarcel\Remote\Particle
        arguments:
            - "%particle_device_id%"
            - "%particle_access_token%"
